version: "2"
networks:
  working:
    external: true
services:
  api:
    build: ./api
    volumes:
      - ./api:/api
    working_dir: /api
    command: python -u run.py
    networks:
      - working
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - api
    networks:
      - working
    ports:
      - 8080:8080
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    networks:
      - working

