version: "2"
networks:
  working:
    external: true
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev
    networks:
      - working
    ports:
      - 8080:8080

